services:
  - type: web
    name: url-preprocessing-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker app:app
    envVars:
      - key: GOOGLE_SAFE_BROWSING_API_KEY
        sync: false
    healthCheckPath: /
    autoDeploy: true 